# Site settings
title: Max Decroy Strandlund
description: Just a blog and some links
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maxxor42.github.io" # the base hostname & protocol for your site
permalink: pretty
paginate: 4
paginate_path: "/blog/:num"

# Build settings
markdown: kramdown
